baseURL = "https://s-peischl.github.io/ABS1/"
publishDir = "docs"
languageCode = "en-us"
title = "Applied Biostatistics I"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    
[[menu.main]]
    name = "Ilias"
    url = "https://ilias.unibe.ch/goto_ilias3_unibe_crs_1793180.html"
    
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/StephanPeischl"
    
[[menu.main]]
    name = "Contact"
    url = "/contact/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo1.png"
    width = 50
    height = 50
    alt = "Logo"
